### ISSUE TITLE
Vigie-Chiro tools review

### ISSUE THREAD

**Issue by bgruening** [Alanamosse/Galaxy-E#47]
* add a [`.shed.yml`](https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/shed_yml.html) file to the repo -> copy this one and adopt it https://github.com/galaxyproject/tools-iuc/blob/master/tools/colibread/.shed.yml
* please add more description to parameters, e.g. here https://github.com/65MO/Galaxy-E/blob/master/tools/Vigie-Chiro/BilanEnrichiPF.xml#L21
  * as a general rule of thumb, try to create tools that are very generic ... so it should be possible to run this tool by also upload a file
* many outputs can be confusing to the user, e.g. here https://github.com/65MO/Galaxy-E/blob/master/tools/Vigie-Chiro/BilanEnrichiPF.xml#L23  You could consider offering a select-box to aks the user if nightly __or__ hourly __or__ summary is wished, or everything.
* do you know about Galaxy macros? https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-macros - its a super cool feature for tools that are very similar or belong to the same class of tools. For example most of your citations are the same across the tool. With macros you can just write them once in a macro file and import them into all tools
  * use macros for citations, requirements and maybe even parameters
* `tail -n +2 output-hourly.html > tmp && mv tmp output-hourly.html` --> `tail -n +2 output-hourly.html > output-hourly.html`
* `label="${tool.name} on ${on_string}"` is the defaul string, so you can remove it if you like.
* there are a lot of csv files in the repo, should there not be an (optional) option to supply this by the user - assuming these files will be updated over time
* general note: Files as https://github.com/65MO/Galaxy-E/blob/master/tools/Vigie-Chiro/test-data/BilanEnrichiPF_Test1_out_tab.tabular are very hard to modify because of the `"`. Why are the quotes needed. Can we remove them in all tools? The idea here is that Galaxy provides a lot of tools for working with tabular files, but they do not have the `"`. You would gain a lot of additional tools and power if we can get rid of them.
* param names like `name="IdC2"` should be written lower-case

**Comment by Alanamosse** [comment]
I checked every tools and applied your comments so I close this issue now. Thanks overall for the precious help, I will apply this to other repos
&nbsp;
>     * add a [`.shed.yml`](https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/shed_yml.html) file to the repo -> copy this one and adopt it https://github.com/galaxyproject/tools-iuc/blob/master/tools/colibread/.shed.yml

I copied the shed.yml but I don't think the "auto_tool_repositories" is optimal as it place some wrong annex files in repositories. I manually listed the files in every repo.
&nbsp;
>       * use macros for citations, requirements and maybe even parameters
Pretty useful :+1: 

&nbsp;
>     * `tail -n +2 output-hourly.html > tmp && mv tmp output-hourly.html` --> `tail -n +2 output-hourly.html > output-hourly.html`
This will not work

&nbsp;
>     * general note: Files as https://github.com/65MO/Galaxy-E/blob/master/tools/Vigie-Chiro/test-data/BilanEnrichiPF_Test1_out_tab.tabular are very hard to modify because of the `"`. Why are the quotes needed. Can we remove them in all tools? The idea here is that Galaxy provides a lot of tools for working with tabular files, but they do not have the `"`. You would gain a lot of additional tools and power if we can get rid of them.
 Did some changes to removes quotes, need some tests

**Comment by bgruening** [comment]
@Alanamosse can you ping me when you are ready with everything. I will try to have then a second pass ...
